/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ScanReportCreateNestedManyWithoutWebsitesInput } from "./ScanReportCreateNestedManyWithoutWebsitesInput";
import { Type } from "class-transformer";
import { ThreatCreateNestedManyWithoutWebsitesInput } from "./ThreatCreateNestedManyWithoutWebsitesInput";
import { FirewallRuleCreateNestedManyWithoutWebsitesInput } from "./FirewallRuleCreateNestedManyWithoutWebsitesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";

@InputType()
class WebsiteCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;

  @ApiProperty({
    required: false,
    type: () => ScanReportCreateNestedManyWithoutWebsitesInput,
  })
  @ValidateNested()
  @Type(() => ScanReportCreateNestedManyWithoutWebsitesInput)
  @IsOptional()
  @Field(() => ScanReportCreateNestedManyWithoutWebsitesInput, {
    nullable: true,
  })
  scanReports?: ScanReportCreateNestedManyWithoutWebsitesInput;

  @ApiProperty({
    required: false,
    type: () => ThreatCreateNestedManyWithoutWebsitesInput,
  })
  @ValidateNested()
  @Type(() => ThreatCreateNestedManyWithoutWebsitesInput)
  @IsOptional()
  @Field(() => ThreatCreateNestedManyWithoutWebsitesInput, {
    nullable: true,
  })
  threats?: ThreatCreateNestedManyWithoutWebsitesInput;

  @ApiProperty({
    required: false,
    type: () => FirewallRuleCreateNestedManyWithoutWebsitesInput,
  })
  @ValidateNested()
  @Type(() => FirewallRuleCreateNestedManyWithoutWebsitesInput)
  @IsOptional()
  @Field(() => FirewallRuleCreateNestedManyWithoutWebsitesInput, {
    nullable: true,
  })
  firewallRules?: FirewallRuleCreateNestedManyWithoutWebsitesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @IsOptional()
  @Field(() => TenantWhereUniqueInput, {
    nullable: true,
  })
  tenant?: TenantWhereUniqueInput | null;
}

export { WebsiteCreateInput as WebsiteCreateInput };
