/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { WebsiteCreateNestedManyWithoutTenantsInput } from "./WebsiteCreateNestedManyWithoutTenantsInput";
import { Type } from "class-transformer";
import { ScanReportCreateNestedManyWithoutTenantsInput } from "./ScanReportCreateNestedManyWithoutTenantsInput";
import { UserCreateNestedManyWithoutTenantsInput } from "./UserCreateNestedManyWithoutTenantsInput";
import { ThreatCreateNestedManyWithoutTenantsInput } from "./ThreatCreateNestedManyWithoutTenantsInput";
import { FirewallRuleCreateNestedManyWithoutTenantsInput } from "./FirewallRuleCreateNestedManyWithoutTenantsInput";

@InputType()
class TenantCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => WebsiteCreateNestedManyWithoutTenantsInput,
  })
  @ValidateNested()
  @Type(() => WebsiteCreateNestedManyWithoutTenantsInput)
  @IsOptional()
  @Field(() => WebsiteCreateNestedManyWithoutTenantsInput, {
    nullable: true,
  })
  websites?: WebsiteCreateNestedManyWithoutTenantsInput;

  @ApiProperty({
    required: false,
    type: () => ScanReportCreateNestedManyWithoutTenantsInput,
  })
  @ValidateNested()
  @Type(() => ScanReportCreateNestedManyWithoutTenantsInput)
  @IsOptional()
  @Field(() => ScanReportCreateNestedManyWithoutTenantsInput, {
    nullable: true,
  })
  scanReports?: ScanReportCreateNestedManyWithoutTenantsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutTenantsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutTenantsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutTenantsInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutTenantsInput;

  @ApiProperty({
    required: false,
    type: () => ThreatCreateNestedManyWithoutTenantsInput,
  })
  @ValidateNested()
  @Type(() => ThreatCreateNestedManyWithoutTenantsInput)
  @IsOptional()
  @Field(() => ThreatCreateNestedManyWithoutTenantsInput, {
    nullable: true,
  })
  threats?: ThreatCreateNestedManyWithoutTenantsInput;

  @ApiProperty({
    required: false,
    type: () => FirewallRuleCreateNestedManyWithoutTenantsInput,
  })
  @ValidateNested()
  @Type(() => FirewallRuleCreateNestedManyWithoutTenantsInput)
  @IsOptional()
  @Field(() => FirewallRuleCreateNestedManyWithoutTenantsInput, {
    nullable: true,
  })
  firewallRules?: FirewallRuleCreateNestedManyWithoutTenantsInput;
}

export { TenantCreateInput as TenantCreateInput };
