/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { WebsiteListRelationFilter } from "../../website/base/WebsiteListRelationFilter";
import { ScanReportListRelationFilter } from "../../scanReport/base/ScanReportListRelationFilter";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";
import { ThreatListRelationFilter } from "../../threat/base/ThreatListRelationFilter";
import { FirewallRuleListRelationFilter } from "../../firewallRule/base/FirewallRuleListRelationFilter";

@InputType()
class TenantWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => WebsiteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WebsiteListRelationFilter)
  @IsOptional()
  @Field(() => WebsiteListRelationFilter, {
    nullable: true,
  })
  websites?: WebsiteListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScanReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScanReportListRelationFilter)
  @IsOptional()
  @Field(() => ScanReportListRelationFilter, {
    nullable: true,
  })
  scanReports?: ScanReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  users?: UserListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ThreatListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ThreatListRelationFilter)
  @IsOptional()
  @Field(() => ThreatListRelationFilter, {
    nullable: true,
  })
  threats?: ThreatListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FirewallRuleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FirewallRuleListRelationFilter)
  @IsOptional()
  @Field(() => FirewallRuleListRelationFilter, {
    nullable: true,
  })
  firewallRules?: FirewallRuleListRelationFilter;
}

export { TenantWhereInput as TenantWhereInput };
