/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Threat } from "./Threat";
import { ThreatCountArgs } from "./ThreatCountArgs";
import { ThreatFindManyArgs } from "./ThreatFindManyArgs";
import { ThreatFindUniqueArgs } from "./ThreatFindUniqueArgs";
import { CreateThreatArgs } from "./CreateThreatArgs";
import { UpdateThreatArgs } from "./UpdateThreatArgs";
import { DeleteThreatArgs } from "./DeleteThreatArgs";
import { Website } from "../../website/base/Website";
import { Tenant } from "../../tenant/base/Tenant";
import { ThreatService } from "../threat.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Threat)
export class ThreatResolverBase {
  constructor(
    protected readonly service: ThreatService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "read",
    possession: "any",
  })
  async _threatsMeta(
    @graphql.Args() args: ThreatCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Threat])
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "read",
    possession: "any",
  })
  async threats(@graphql.Args() args: ThreatFindManyArgs): Promise<Threat[]> {
    return this.service.threats(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Threat, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "read",
    possession: "own",
  })
  async threat(
    @graphql.Args() args: ThreatFindUniqueArgs
  ): Promise<Threat | null> {
    const result = await this.service.threat(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Threat)
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "create",
    possession: "any",
  })
  async createThreat(@graphql.Args() args: CreateThreatArgs): Promise<Threat> {
    return await this.service.createThreat({
      ...args,
      data: {
        ...args.data,

        website: args.data.website
          ? {
              connect: args.data.website,
            }
          : undefined,

        tenant: args.data.tenant
          ? {
              connect: args.data.tenant,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Threat)
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "update",
    possession: "any",
  })
  async updateThreat(
    @graphql.Args() args: UpdateThreatArgs
  ): Promise<Threat | null> {
    try {
      return await this.service.updateThreat({
        ...args,
        data: {
          ...args.data,

          website: args.data.website
            ? {
                connect: args.data.website,
              }
            : undefined,

          tenant: args.data.tenant
            ? {
                connect: args.data.tenant,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Threat)
  @nestAccessControl.UseRoles({
    resource: "Threat",
    action: "delete",
    possession: "any",
  })
  async deleteThreat(
    @graphql.Args() args: DeleteThreatArgs
  ): Promise<Threat | null> {
    try {
      return await this.service.deleteThreat(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Website, {
    nullable: true,
    name: "website",
  })
  @nestAccessControl.UseRoles({
    resource: "Website",
    action: "read",
    possession: "any",
  })
  async getWebsite(@graphql.Parent() parent: Threat): Promise<Website | null> {
    const result = await this.service.getWebsite(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Tenant, {
    nullable: true,
    name: "tenant",
  })
  @nestAccessControl.UseRoles({
    resource: "Tenant",
    action: "read",
    possession: "any",
  })
  async getTenant(@graphql.Parent() parent: Threat): Promise<Tenant | null> {
    const result = await this.service.getTenant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
