/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FirewallRuleService } from "../firewallRule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FirewallRuleCreateInput } from "./FirewallRuleCreateInput";
import { FirewallRule } from "./FirewallRule";
import { FirewallRuleFindManyArgs } from "./FirewallRuleFindManyArgs";
import { FirewallRuleWhereUniqueInput } from "./FirewallRuleWhereUniqueInput";
import { FirewallRuleUpdateInput } from "./FirewallRuleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FirewallRuleControllerBase {
  constructor(
    protected readonly service: FirewallRuleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FirewallRule })
  @nestAccessControl.UseRoles({
    resource: "FirewallRule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFirewallRule(
    @common.Body() data: FirewallRuleCreateInput
  ): Promise<FirewallRule> {
    return await this.service.createFirewallRule({
      data: {
        ...data,

        website: data.website
          ? {
              connect: data.website,
            }
          : undefined,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        ruleName: true,
        ruleDetails: true,

        website: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FirewallRule] })
  @ApiNestedQuery(FirewallRuleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FirewallRule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async firewallRules(@common.Req() request: Request): Promise<FirewallRule[]> {
    const args = plainToClass(FirewallRuleFindManyArgs, request.query);
    return this.service.firewallRules({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        ruleName: true,
        ruleDetails: true,

        website: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FirewallRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FirewallRule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async firewallRule(
    @common.Param() params: FirewallRuleWhereUniqueInput
  ): Promise<FirewallRule | null> {
    const result = await this.service.firewallRule({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        ruleName: true,
        ruleDetails: true,

        website: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FirewallRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FirewallRule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFirewallRule(
    @common.Param() params: FirewallRuleWhereUniqueInput,
    @common.Body() data: FirewallRuleUpdateInput
  ): Promise<FirewallRule | null> {
    try {
      return await this.service.updateFirewallRule({
        where: params,
        data: {
          ...data,

          website: data.website
            ? {
                connect: data.website,
              }
            : undefined,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          ruleName: true,
          ruleDetails: true,

          website: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FirewallRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FirewallRule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFirewallRule(
    @common.Param() params: FirewallRuleWhereUniqueInput
  ): Promise<FirewallRule | null> {
    try {
      return await this.service.deleteFirewallRule({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          ruleName: true,
          ruleDetails: true,

          website: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
